import type { NextPage } from 'next'
import {Button} from 'antd';
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.title}>
          Welcome to Online School!
        </h1>
        <div className={styles.homeButton}>
          <Button type='default'>
            <Link href='/Login'>Log in</Link>
          </Button>
          <Button type='primary'>
            <Link href='/signUp'>Sign up</Link>
          </Button>
        
        </div>
        
    </div>
  )
}

export default Home
